Repository sumana2001/python, pull requests merged in 2020-10, with the labels that each got.

#30 Guess the Number
  Numberguess.py
Labels: hacktober2020, hacktoberfest

#20 Instagram Bot
  InstagramBot/Instabot.py
  InstagramBot/README.md
Labels: hacktober2020, hacktoberfest, python

#43 Added Python assistant Project
  Assistant Py/README.md
  Assistant Py/py-assist.py
Labels: hacktober2020, hacktoberfest, python

#18 Add binary search algorithm
  binarySearch.py
Labels: hacktober2020, hacktoberfest, python

#45 added port-scanner written in Python
  port-scanner.py
Labels: hacktober2020, hacktoberfest, python

#19 Adding GUI-QrCodeGenerator and Calculator
  Basic-Calculator/Calci.py
  Basic-Calculator/README.md
  Basic-Calculator/Sample.jpg
  QR-Code-Generator/README.md
  QR-Code-Generator/Sample.jpg
  QR-Code-Generator/qrcodegen.py
  QR-Code-Generator/requirements.txt
  Youtube Downloader/README.md
  Youtube Downloader/YTdownloader.py
  Youtube Downloader/Yt.png
  Youtube Downloader/requirements.txt
  Youtube Downloader/sample.jpg
Labels: hacktober2020, hacktoberfest, python

#50 Find duplicate files by comparing hashes of files
  Utility/FindDuplicateFilesInDirectory.py
Labels: hacktober2020, hacktoberfest, python

#29 Add files via upload
  Number Plate/From Image/Number Plate From Image.py
  Number Plate/From Image/haarcascade_russian_plate_number.xml
  Number Plate/From Image/sample images/im.jpg
  Number Plate/From Image/sample images/im1.jpg
  Number Plate/From Image/sample images/im2.jpg
  Number Plate/From Image/sample images/im3.jpg
  Number Plate/From Video/Number Plate From Video.py
  Number Plate/From Video/haarcascade_russian_plate_number.xml
  rock-paper-scissors-master/gather_images.py
  rock-paper-scissors-master/images/paper.png
  rock-paper-scissors-master/images/rock.png
  rock-paper-scissors-master/images/scissors.png
  rock-paper-scissors-master/play.py
Labels: hacktober2020, hacktoberfest

#61 A basic web scraper code
  webscraper/README.md
  webscraper/WebScraper.py
  webscraper/cli.png
  webscraper/samp.png
Labels: hacktober2020, hacktoberfest

#60 Create png to jpg.py
  png to jpg.py
Labels: hacktober2020, hacktoberfest

#64 Create Notepad
  Notepad
Labels: hacktober2020, hacktoberfest, python

#65 Added Hangman Game in python along with its documentation
  Hangman-Game/hangman.py
  Hangman-Game/readme.md
Labels: hacktober2020, hacktoberfest

#69 Imported IRC_Bot repo
  IRC_bot/Dockerfile
  IRC_bot/LICENSE
  IRC_bot/README.md
  IRC_bot/commands.py
  IRC_bot/config.json
  IRC_bot/default_config.json
  IRC_bot/docs/CODE_OF_CONDUCT.md
  IRC_bot/docs/CONTRIBUTING.md
  IRC_bot/main.py
  IRC_bot/modules/covid19.py
  IRC_bot/modules/draw_card.py
  IRC_bot/modules/horoscope.py
  IRC_bot/modules/jesus.py
  IRC_bot/modules/jokes.py
  IRC_bot/modules/quote_day.py
  IRC_bot/modules/random_cat.py
  IRC_bot/modules/random_cat_fact.py
  IRC_bot/modules/random_dog.py
  IRC_bot/modules/roll.py
  IRC_bot/modules/sentiment.py
  IRC_bot/modules/urban_dictionary.py
  IRC_bot/modules/wiki_summary.py
  IRC_bot/requirements.txt
  IRC_bot/testkit.py
  IRC_bot/tests.txt
Labels: hacktober2020, hacktoberfest

#84 added sentiment analysis using word2vec
  Sentiment Analysis using Word2Vec/agr_en_train.csv
  Sentiment Analysis using Word2Vec/sentimentAnalysis.ipynb
Labels: hacktober2020, hacktoberfest

#87 Currency converter solution added Issue#83
  .vscode/settings.json
  README.md
  currency converter/main.py
Labels: hacktober2020, hacktoberfest

#88 TicTacToe game in python
  TicTacToe Game/README.md
  TicTacToe Game/TicTacToe.py
  TicTacToe Game/screenShot.PNG
Labels: hacktober2020, hacktoberfest

#90 add cc validator
  Utility/CCValidator.py
Labels: hacktober2020, hacktoberfest

#97 Solution to Issue #78 (Website Blocker)
  Website-Blocker/README.md
  Website-Blocker/websiteBlocker.py
Labels: hacktober2020, hacktoberfest

#94 Added Pdf_Reader.py
  PDF_Reader.py
Labels: hacktober2020, hacktoberfest, python

#91 solve issue#79 screenshot-taker
  .vscode/settings.json
  screenshot-Taker/main.py
Labels: hacktober2020, hacktoberfest, python

#99 Added Video player
  .gitignore
  VIdeo Player/README.md
  VIdeo Player/main.py
  VIdeo Player/mercury.jpeg
  VIdeo Player/requirements.txt
  VIdeo Player/sample.jpg
Labels: hacktober2020, hacktoberfest, python

#100 Added blackjack solve issues #71
  blackJack/main.py
  passwordManager/info.txt
  passwordManager/main.py
Labels: hacktober2020, hacktoberfest, python

#105 Added Screen recorder
  .vscode/settings.json
  Screen Recorder/README.md
  Screen Recorder/main.py
  Screen Recorder/requirements.txt
  Screen Recorder/sample.jpg
Labels: hacktober2020, hacktoberfest

#106 Adding a heart disease classifier
  Heart-Disease-Classifier/heart-disease.csv
  Heart-Disease-Classifier/heart_disease_classifier.ipynb
  Heart-Disease-Classifier/readme.txt
Labels: hacktober2020, hacktoberfest

#107 Face Detection implementation in python using openCV
  Face_Detect/face_detect.py
  Face_Detect/face_detect_Screenshot.png
  Face_Detect/haarcascade_frontalface_default.xml
  Face_Detect/image1.jpg
Labels: hacktober2020, hacktoberfest, python

#109 Added OpenCV Background Detector with 2 examples
  OpenCV/Background_Detector/Background_Detector.py
  OpenCV/Background_Detector/Car.mp4
  OpenCV/Background_Detector/Car_background.jpg
  OpenCV/Background_Detector/Sevilla.mp4
  OpenCV/Background_Detector/Sevilla_background.jpg
Labels: hacktober2020, hacktoberfest, hacktoberfest-accepted

#111 Loan Prediction using Machine Learning #24
  Loan Prediction model/README.md
  Loan Prediction model/dataset/test_Y3wMUE5_7gLdaTN.csv
  Loan Prediction model/dataset/train_u6lujuX_CVtuZ9i.csv
  Loan Prediction model/main.py
Labels: hacktober2020, hacktoberfest, hacktoberfest-accepted, python

#116 Added Face recognition attendence system
  Face_Recognition_Attendance_System/Narendra_Modi.jpg
  Face_Recognition_Attendance_System/Sundar-Pichai.jpg
  Face_Recognition_Attendance_System/attendance_list.csv
  Face_Recognition_Attendance_System/face_recognition_attendance_system.py
  Face_Recognition_Attendance_System/mukesh-ambani.jpg
  Face_Recognition_Attendance_System/uk_Narendra_Modi.jpg
  Face_Recognition_Attendance_System/uk_Sundar-Pichai.jpg
  Face_Recognition_Attendance_System/uk_mukesh-ambani.jpg
Labels: hacktoberfest, hacktoberfest-accepted, python

#114 Solution to Issue #75 (Mass Mail Sender)
  Mass-Mail-Sender/README.md
  Mass-Mail-Sender/mailSender.py
Labels: hacktoberfest, hacktoberfest-accepted

#113 added twitter-bot #31
  twitter-bot/README.md
  twitter-bot/config.py
  twitter-bot/credentials.py
  twitter-bot/twitterbot_retweet.py
Labels: hacktoberfest, hacktoberfest-accepted

#117 Library management system
  Library mangement system/main.exe
  Library mangement system/main.py
  Library mangement system/main.spec
  Library mangement system/readme.md
Labels: hacktober2020, hacktoberfest, hacktoberfest-accepted

#123 added meme generator and password generator in Python
  memeGenerator.py
  passwordGenerator.py
Labels: hacktober2020, hacktoberfest, hacktoberfest-accepted

#124 added email automation in python
  emailAutomation.py
Labels: hacktober2020, hacktoberfest, hacktoberfest-accepted

#125 added Google news in python
  googleNews.py
Labels: hacktoberfest, hacktoberfest-accepted

#128 Image_Filter_Blur
  Image_Filter-Blur.py
Labels: hacktober2020, hacktoberfest, hacktoberfest-accepted

#127 added sarcasm headlines nlp
  Sarcastic-Headlines-Model/NLP.ipynb
  Sarcastic-Headlines-Model/readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#130 Added pychat program
  pychat/Readme.txt
  pychat/pychat.py
  pychat/server.py
Labels: hacktober2020, hacktoberfest, hacktoberfest-accepted

#132 Vertical Concatenation in Matrix
  verticalConcatenationMatrix
Labels: hacktoberfest, hacktoberfest-accepted
